const planets=[
 {id:'gas',name:'GASVERSE',emoji:'🧪',topic:'กฎของแก๊ส',desc:'บอยล์ ชาร์ล อาโวกาโดร และ PV=nRT',color:'pink'},
 {id:'electro',name:'ELECTROVERSE',emoji:'⚡',topic:'ไฟฟ้า',desc:'วงจร กระแส ความต่างศักย์ และความต้านทาน'},
 {id:'cell',name:'CELLVERSE',emoji:'🧬',topic:'เซลล์',desc:'ออร์แกเนลล์ การลำเลียงสาร และพลังงานเซลล์'},
 {id:'eco',name:'ECOVERSE',emoji:'🌍',topic:'ระบบนิเวศ',desc:'สายใยอาหาร ประชากร และสมดุลธรรมชาติ'},
 {id:'geo',name:'GEOVERSE',emoji:'🌋',topic:'โลกและธรณี',desc:'หิน แผ่นเปลือกโลก ภูเขาไฟ และแผ่นดินไหว'},
 {id:'space',name:'SPACEVERSE',emoji:'🪐',topic:'ดาราศาสตร์',desc:'ดาวเคราะห์ ดาวฤกษ์ กาแล็กซี และจักรวาล'},
 {id:'force',name:'FORCEVERSE',emoji:'🧲',topic:'แรงและการเคลื่อนที่',desc:'แรง มวล ความเร่ง และพลังงาน'},
 {id:'chemi',name:'CHEMIVERSE',emoji:'🧫',topic:'สารและปฏิกิริยา',desc:'อะตอม โมเลกุล สมการเคมี และปฏิกิริยา'}
];
const missions={
 gas:[
  {title:'Boyle City ระเบิดความดัน',q:'ถ้าอุณหภูมิคงที่ แล้วความดันเพิ่มขึ้น 2 เท่า ปริมาตรของแก๊สจะเป็นอย่างไร?',opts:['เพิ่มขึ้น 2 เท่า','ลดลงครึ่งหนึ่ง','คงที่','เพิ่มขึ้น 4 เท่า'],ans:1,exp:'กฎของบอยล์: P แปรผกผันกับ V เมื่อ T คงที่ ดังนั้น P เพิ่ม 2 เท่า V ลดครึ่งหนึ่ง'},
  {title:'Charles Balloon',q:'เมื่อความดันคงที่ ถ้าอุณหภูมิของแก๊สเพิ่มขึ้น ปริมาตรจะเป็นอย่างไร?',opts:['ลดลง','เพิ่มขึ้น','ไม่เปลี่ยน','กลายเป็นของเหลว'],ans:1,exp:'กฎของชาร์ล: V แปรผันตรงกับ T หน่วยเคลวิน เมื่อ T เพิ่ม V เพิ่ม'},
  {title:'Ideal Gas Castle',q:'สมการแก๊สอุดมคติคือข้อใด?',opts:['P+V=nRT','PV=nRT','P/V=nRT','PT=nRV'],ans:1,exp:'สมการแก๊สอุดมคติคือ PV=nRT ใช้เชื่อม P,V,n,T'}
 ],
 electro:[{title:'Circuit Gate',q:'สูตรกฎของโอห์มคือข้อใด?',opts:['V=IR','P=mv','F=ma','Q=mcΔT'],ans:0,exp:'กฎของโอห์มคือ V=IR ความต่างศักย์ = กระแส × ความต้านทาน'}],
 cell:[{title:'Cell Core',q:'ออร์แกเนลล์ใดทำหน้าที่ควบคุมกิจกรรมของเซลล์?',opts:['ไรโบโซม','นิวเคลียส','ไมโทคอนเดรีย','แวคิวโอล'],ans:1,exp:'นิวเคลียสมีสารพันธุกรรมและควบคุมการทำงานของเซลล์'}],
 eco:[{title:'Food Web Rescue',q:'ผู้ผลิตในระบบนิเวศมักหมายถึงสิ่งมีชีวิตกลุ่มใด?',opts:['เสือ','เห็ดรา','พืชสีเขียว','แบคทีเรียย่อยสลาย'],ans:2,exp:'พืชสีเขียวสังเคราะห์ด้วยแสง สร้างอาหารเองได้ จึงเป็นผู้ผลิต'}],
 geo:[{title:'Volcano Signal',q:'หินอัคนีเกิดจากอะไร?',opts:['ตะกอนทับถม','แมกมา/ลาวาเย็นตัว','ซากพืชสัตว์','น้ำทะเลระเหย'],ans:1,exp:'หินอัคนีเกิดจากแมกมาหรือลาวาเย็นตัวและแข็งตัว'}],
 space:[{title:'Orbit Path',q:'ดาวเคราะห์โคจรรอบสิ่งใดในระบบสุริยะ?',opts:['ดวงจันทร์','โลก','ดวงอาทิตย์','ดาวหาง'],ans:2,exp:'ดาวเคราะห์ในระบบสุริยะโคจรรอบดวงอาทิตย์'}],
 force:[{title:'Newton Bridge',q:'สูตรกฎข้อที่ 2 ของนิวตันคือข้อใด?',opts:['F=ma','PV=nRT','V=IR','E=mc²'],ans:0,exp:'แรงลัพธ์เท่ากับมวลคูณความเร่ง หรือ F=ma'}],
 chemi:[{title:'Reaction Lab',q:'สารตั้งต้นในปฏิกิริยาเคมีเรียกว่าอะไร?',opts:['Product','Reactant','Catalyst','Solvent'],ans:1,exp:'Reactant คือสารตั้งต้น Product คือผลิตภัณฑ์'}]
};
let state=JSON.parse(localStorage.getItem('scienceverse-state')||'{}');
state={name:state.name||'นักสำรวจดาววิทย์',xp:state.xp||0,level:state.level||1,stars:state.stars||0,badges:state.badges||[],completed:state.completed||{},currentPlanet:null,currentMission:0,score:0,lives:3,...state};
const app=document.getElementById('app');
function save(){state.level=Math.floor(state.xp/100)+1;localStorage.setItem('scienceverse-state',JSON.stringify(state));}
function setRoute(route,param){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===route)); if(route==='home')home(); if(route==='map')map(); if(route==='profile')profile(); if(route==='library')library(); if(route==='teacher')teacher(); if(route==='planet')planet(param); if(route==='play')play(param); if(route==='result')result(); window.scrollTo(0,0)}
document.querySelector('.bottom-nav').addEventListener('click',e=>{const b=e.target.closest('button'); if(b)setRoute(b.dataset.route)});
function home(){app.innerHTML=`<section class="hero"><div class="hero-card glass"><div class="orbit"></div><span class="badge">🌌 SCIENCEVERSE Academy</span><h1 class="title">จักรวาลวิทย์<br>พิชิตภารกิจ</h1><p class="subtitle">แพลตฟอร์มเกมวิทยาศาสตร์ภาษาไทย นักเรียนเดินทางผ่านดาวความรู้ เก็บ XP ปลดล็อก Badge และเรียนรู้แบบ RPG</p><div class="stat-row"><div class="stat glass"><b>${state.level}</b><span>Level</span></div><div class="stat glass"><b>${state.xp}</b><span>XP</span></div><div class="stat glass"><b>${state.stars}</b><span>Stars</span></div></div><div class="xpbar"><div class="xpfill" style="width:${state.xp%100}%"></div></div><div class="actions"><button class="btn primary" onclick="setRoute('map')">🚀 เริ่มภารกิจ</button><button class="btn ghost" onclick="setRoute('library')">📚 คลังความรู้</button></div></div></section>`}
function map(){app.innerHTML=`<div class="section-head"><div><h1>🌌 Galaxy Map</h1><p class="mini">เลือกดาว แล้วเข้าสู่ภารกิจวิทยาศาสตร์</p></div><span class="pill">Level ${state.level}</span></div><section class="grid">${planets.map(p=>`<article class="planet glass" onclick="setRoute('planet','${p.id}')"><div class="emoji">${p.emoji}</div><h2>${p.name}</h2><span class="pill">${p.topic}</span><p>${p.desc}</p><small>⭐ ผ่านแล้ว ${state.completed[p.id]||0} ภารกิจ</small></article>`).join('')}</section>`}
function planet(id){const p=planets.find(x=>x.id===id); state.currentPlanet=id; save(); const ms=missions[id]||[]; app.innerHTML=`<div class="section-head"><div><h1>${p.emoji} ${p.name}</h1><p class="mini">${p.desc}</p></div><button class="btn ghost" onclick="setRoute('map')">กลับแผนที่</button></div><div class="card glass dialogue"><div class="npc">👩‍🔬</div><div><b>ดร.นิวตรอน</b><p class="mini">ยินดีต้อนรับสู่ ${p.name}! เลือกภารกิจเพื่อกู้ระบบความรู้ของดาวนี้</p></div></div><h2>ภารกิจ</h2>${ms.map((m,i)=>`<div class="mission"><div><b>${i+1}. ${m.title}</b><p class="mini">ตอบคำถาม รับ XP และดาวภารกิจ</p></div><button class="btn primary" onclick="startMission(${i})">เล่น</button></div>`).join('')}`}
function startMission(i){state.currentMission=i;state.score=0;state.lives=3;save();setRoute('play')}
function play(){const id=state.currentPlanet||'gas'; const m=(missions[id]||missions.gas)[state.currentMission||0]; app.innerHTML=`<div class="section-head"><div><h1>🎮 ${m.title}</h1><p class="mini">ชีวิต ${'❤️'.repeat(state.lives)} | คะแนน ${state.score}</p></div><span class="pill">${planets.find(p=>p.id===id)?.name}</span></div><div class="card glass"><div class="dialogue"><div class="npc">🤖</div><div><b>AI Lab</b><p class="mini">อ่านสถานการณ์ แล้วเลือกคำตอบที่เหมาะสมที่สุด</p></div></div><p class="question">${m.q}</p><div class="options">${m.opts.map((o,i)=>`<button class="option" onclick="answer(${i})">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div><div id="feedback"></div></div>`}
function answer(i){const id=state.currentPlanet||'gas'; const m=(missions[id]||missions.gas)[state.currentMission||0]; const fb=document.getElementById('feedback'); if(i===m.ans){state.score+=100;state.xp+=35;state.stars+=1;state.completed[id]=(state.completed[id]||0)+1;const badge=planets.find(p=>p.id===id).name+' Explorer'; if(!state.badges.includes(badge))state.badges.push(badge);save();fb.innerHTML=`<div class="feedback ok">✅ ถูกต้อง! +35 XP<br>${m.exp}<br><br><button class="btn primary" onclick="setRoute('result')">ดูผลลัพธ์</button></div>`}else{state.lives-=1;save();fb.innerHTML=`<div class="feedback bad">💡 ยังไม่ใช่คำตอบน้า<br>${m.exp}<br><br><button class="btn primary" onclick="${state.lives>0?'play()':'setRoute(\'result\')'}">${state.lives>0?'ลองใหม่':'ดูผลลัพธ์'}</button></div>`}}
function result(){let rank=state.score>=100?'ปรมาจารย์ SCIENCEVERSE':'นักสำรวจดาววิทย์ฝึกหัด'; app.innerHTML=`<div class="hero"><div class="hero-card glass"><span class="badge">🏆 Result</span><h1 class="title">ภารกิจสำเร็จ!</h1><p class="subtitle">ระดับของคุณ: <b>${rank}</b></p><div class="stat-row"><div class="stat glass"><b>${state.score}</b><span>คะแนนรอบนี้</span></div><div class="stat glass"><b>${state.xp}</b><span>XP รวม</span></div><div class="stat glass"><b>${state.badges.length}</b><span>Badge</span></div></div><div class="actions"><button class="btn primary" onclick="setRoute('map')">🌌 เล่นดาวอื่น</button><button class="btn ghost" onclick="setRoute('library')">📚 ทบทวนสูตร</button></div></div></div>`}
function profile(){app.innerHTML=`<div class="section-head"><div><h1>🧑‍🚀 Student Profile</h1><p class="mini">ข้อมูลผู้เล่นบันทึกในเครื่องนี้ด้วย localStorage</p></div></div><div class="card glass"><label>ชื่อผู้เล่น</label><input style="width:100%;margin:8px 0 14px;padding:14px;border-radius:16px;border:0;font-size:16px" value="${state.name}" onchange="state.name=this.value;save();profile()"><div class="stat-row"><div class="stat glass"><b>${state.level}</b><span>Level</span></div><div class="stat glass"><b>${state.xp}</b><span>XP</span></div><div class="stat glass"><b>${state.stars}</b><span>Stars</span></div></div><h2>Badge Collection</h2><div class="grid">${(state.badges.length?state.badges:['ยังไม่มี Badge ลองเริ่มภารกิจแรกเลย']).map(b=>`<div class="card glass">🏅 ${b}</div>`).join('')}</div><br><button class="btn ghost" onclick="localStorage.removeItem('scienceverse-state');location.reload()">รีเซ็ตข้อมูล</button></div>`}
function library(){app.innerHTML=`<div class="section-head"><div><h1>📚 Knowledge Library</h1><p class="mini">สรุปสูตรและแก่นความรู้สำหรับทบทวน</p></div></div><div class="grid"><div class="card glass"><h2>🧪 GASVERSE</h2><div class="formula">Boyle: P₁V₁=P₂V₂</div><div class="formula">Charles: V₁/T₁=V₂/T₂</div><div class="formula">Avogadro: V ∝ n</div><div class="formula">Ideal Gas: PV=nRT</div></div><div class="card glass"><h2>⚡ ELECTROVERSE</h2><div class="formula">Ohm: V=IR</div><div class="formula">Power: P=VI</div></div><div class="card glass"><h2>🧲 FORCEVERSE</h2><div class="formula">Newton 2: F=ma</div><div class="formula">Work: W=Fs</div></div><div class="card glass"><h2>🌍 ECOVERSE</h2><div class="formula">ผู้ผลิต → ผู้บริโภค → ผู้ย่อยสลาย</div></div></div>`}
function teacher(){app.innerHTML=`<div class="section-head"><div><h1>👩‍🏫 Teacher Dashboard</h1><p class="mini">โหมดครูสำหรับดูภาพรวมและใช้เป็นกิจกรรมในชั้นเรียน</p></div></div><div class="card glass"><table class="teacher-table"><tr><th>รายการ</th><th>ข้อมูล</th></tr><tr><td>ผู้เล่น</td><td>${state.name}</td></tr><tr><td>Level</td><td>${state.level}</td></tr><tr><td>XP</td><td>${state.xp}</td></tr><tr><td>ดาวสะสม</td><td>${state.stars}</td></tr><tr><td>Badge</td><td>${state.badges.join(', ')||'-'}</td></tr></table><br><button class="btn primary" onclick="window.print()">🖨️ พิมพ์/บันทึกรายงาน</button></div><div class="card glass" style="margin-top:14px"><h2>ไอเดียใช้ในห้องเรียน</h2><p class="mini">แบ่งกลุ่ม 3-5 คน เลือกดาวคนละ 1 ด่าน แข่งเก็บ XP แล้วให้สรุปสูตร/แนวคิดหลังเล่น</p></div>`}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}
home();
